# web 应用名称
name: "gin-web"
# web 应用端口
port: 8080
logs_address: "./logs/"

# mysql 相关配置
mysql:
  # mysql 账号
  name: "root"
  # mysql 地址
  host: "127.0.0.1"
  # mysql 端口
  port: 3306
  # mysql 密码
  password: "xxxxxx"
  # 数据库名称
  db_name: "test"

# redis 相关配置
redis:
  # redis 地址
  host: "127.0.0.1"
  # redis 端口
  port: 6379
  # redis 密码
  password: "xxxxxx"